FROM mcr.microsoft.com/mssql/server:2017-latest
ARG AUTH_PLUGIN
ENV AUTH_PLUGIN=$AUTH_PLUGIN

ARG HOST
ENV HOST=$HOST

ARG PORT
ENV PORT=$PORT

ARG MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

ARG USER
ENV USER=$USER
COPY . . 
WORKDIR /src
EXPOSE 3306 
RUN (/opt/mssql/bin/sqlservr --accept-eula & )
