FROM mcr.microsoft.com/mssql/server:2017-latest
ARG AUTH_PLUGIN
ARG HOST
ARG PORT
ARG MYSQL_ROOT_PASSWORD
ARG USER
ENV AUTH_PLUGIN=$AUTH_PLUGIN
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ENV USER=$USER
ENV HOST=$HOST
ENV PORT=$PORT
WORKDIR /src
EXPOSE 3306 
RUN (/opt/mssql/bin/sqlservr --accept-eula & )
