trigger: none
pool:
  name: 'Default'
  demands:
    - agent.name -equals SWK

variables:
- group: pythonDetails
- group: sqlDetails

resources:
  repositories:
  - repository: ING # The name used to reference this repository in the checkout step
    type: github
    name: chitulescui/ING
    endpoint: chitulescui
    ref: developer   

stages:

- stage: Build_And_Run_Docker_Image
  jobs:
  - job: Docker_Build
    steps:
      - checkout: ING
      - powershell: docker build . -t chitulescui/sqlserver
  - job: Run_Docker_Container
    steps:
      - checkout: ING
      - powershell: docker run --name some-mysql -p $(MYPORT):$(MYPORT) -e $(ACCEPT_EULA) -e "MSSQL_SA_PASSWORD=$(MSSQL_ROOT_PASSWORD)" -d chitulescui/sqlserver
                                                           

        displayName: DockerMySql
    dependsOn: Docker_Build
# 
- stage: Run_Python_Script
  jobs:
  - job: Python
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        scriptPath: '$(scriptPath)'
        pythonInterpreter: '$(pythonInterpreter)'
  
  
         # Run MegaLinter
        # - powershell: |
            # docker run -v $(System.DefaultWorkingDirectory):/tmp/lint -e SYSTEM_ACCESSTOKEN=$(System.AccessToken) -e GIT_AUTHORIZATION_BEARER=$(System.AccessToken) --name MegaLinter oxsecurity/megalinter:latest
          # displayName: Run MegaLinter
        # 
        # Upload MegaLinter reports
        # - task: PublishPipelineArtifact@1
          # condition: succeededOrFailed()
          # displayName: Upload MegaLinter reports
          # inputs:
            # targetPath: "$(System.DefaultWorkingDirectory)/megalinter-reports/"
            # artifactName: MegaLinterReport