trigger: none
pool:
  name: 'Default'
  demands:
    - agent.name -equals SWK

variables:
- group: pythonVariables
- group: sqlVariables

resources:
  repositories:
  - repository: ING # The name used to reference this repository in the checkout step
    type: github
    name: chitulescui/ING
    endpoint: chitulescui
    ref: main   

stages:
# - stage: Build_And_Run_Docker_Image
  # jobs:
  # - job: Docker_Build
    # steps:
      # - checkout: ING
      # - powershell: docker build . -t chitulescui/sqlserver
  # - job: Run_Docker_Container
    # steps:
      # - checkout: ING
      # - powershell: docker run --name some-mysql -p $(PORT):$(PORT) -e $(ACCEPT_EULA) -e "MSSQL_SA_PASSWORD=$(MSSQL_ROOT_PASSWORD)" -d chitulescui/sqlserver
    # displayName: Docker_Run
    # dependsOn: Docker_Build
# 
- stage: Run_Python_Script
  jobs:
  - job: Python
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        scriptPath: '$(scriptPath)'
        pythonInterpreter: '$(pythonInterpreter)'

- stage: Publish_Python_Artifact
  jobs: 
  - job: Publish_Python_Artifact
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Upload_JSON_File
      inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/jsontryfilebun.json'
          artifact: 'jsontryfilebun.json'
          publishLocation: 'pipeline'